#!/bin/sh /etc/rc.common

START=20
USE_PROCD=1

service_triggers()
{
	procd_add_reload_trigger "easybox"
}

start_service() {
	local status_led power_led power_led_br

	config_load easybox
	config_get_bool power_led "settings" power_led
	
	if [ $power_led -eq 0 ]; then
		ubus call led.power set '{"state": "off"}'
	else
		ubus call led.power set '{"state": "ok"}'
	fi
}

