#! /bin/sh

# record that we are doing a manual reboot
# this to be able to detect a reboot done by watchdog

if [ -n "$REBOOT_REASON" ]
then
    echo $REBOOT_REASON >/etc/reboot
else
    echo manual >/etc/reboot
fi

sync
/bin/busybox reboot $@

