#! /bin/sh

# record that we are doing a manual reboot
# this to be able to detect a reboot done by watchdog

# if no reason then set manual
if [ -z "$REBOOT_REASON" ]
then
    REBOOT_REASON="manual"
fi

# First try the overlay this maight fail
echo $REBOOT_REASON 2>/dev/null >/etc/reboot
if [ $? != 0 ]
then
    # overlayfs gave error probably a defaultreset try the main filesystem
    echo $REBOOT_REASON >/rom/etc/reboot
fi

sync
/bin/busybox reboot $@

