#!/bin/sh

set_preinit_iface() {
	ifname=eth1

	. /lib/brcm63xx.sh	

	ifconfig $ifname 0.0.0.0 up
}

check_module () {
  module="$1"; shift; params="$*"

  insmod "$module" "$params"
  sleep 1
  grep "^$module" /proc/modules
  return $?
}

boot_hook_add preinit_main set_preinit_iface
