./scripts/feeds update
./scripts/feeds install asterisk18
./scripts/feeds install libexpat
./scripts/feeds uninstall asterisk18
./scripts/feeds install libflac
./scripts/feeds install libvorbis
./scripts/feeds install libogg
./scripts/feeds install libid3tag
./scripts/feeds install libexif
./scripts/feeds install libsqlite3
./scripts/feeds install libffmpeg
./scripts/feeds install libjpeg
./scripts/feeds install libusb
./scripts/feeds install usb-modeswitch-data
./scripts/feeds install usb-modeswitch
./scripts/feeds install strace
./scripts/feeds install libevent2
./scripts/feeds install libpng
./scripts/feeds install iperf
./scripts/feeds install curl
./scripts/feeds install libcurl
./scripts/feeds install liblzo
./scripts/feeds install miniupnpd
./scripts/feeds install minidlna
./scripts/feeds install tcpdump
./scripts/feeds install smap
./scripts/feeds install smap-to-devinfo
./scripts/feeds install ddns-script
./scripts/feeds install hd-idle
./scripts/feeds install multiwan
./scripts/feeds install ntpclient
./scripts/feeds install collecd-mod-olsrd
./scripts/feeds install openvpn
./scripts/feeds install p10nd
./scripts/feeds install polipo
./scripts/feeds install radvd
./scripts/feeds install snmpd
./scripts/feeds install tinyproxy
./scripts/feeds install transmission
./scripts/feeds install ushare
./scripts/feeds install vnstat
./scripts/feeds install watchcat
./scripts/feeds install etherwake
./scripts/feeds install wshaper
./scripts/feeds install syslog-ng3
./scripts/feeds install bind
./scripts/feeds install bind-tools
./scripts/feeds install logrotate
./scripts/feeds install ndisc6
./scripts/feeds install libpcre
./scripts/feeds install libxml2
./scripts/feeds install lighttpd
