#!/bin/sh 

# Author: Martin K. Schröder <mkschreder.uk@gmail.com>

# The new genconfig script works by copying all base system options from the master
# config and then using the builtin menuconfig Makefiles to setup all dependencies. 
# This means that in order to get a package built only one specific system and not for the 
# others, you need to make sure that the package is not already selected in the master config
# Any other packages that you want to select for a specific model/customer you should set
# in the model and customer makefiles as package dependencies to the given model/customer package

CONFIG=.config

cp package/inteno/configs/MASTER/config ${CONFIG}
echo "CONFIG_PACKAGE_routermodel-${1}=y" >> ${CONFIG}
make defconfig 
