#!/bin/sh /etc/rc.common

START=14
STOP=96

USE_PROCD=1
NAME=questd
PROG=/sbin/questd

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn
	procd_close_instance
}

stop() {
	service_stop /sbin/questd
}

service_triggers()
{
	procd_add_reload_trigger network wireless
}

reload() {
	ubus call router reload
}

