#!/bin/sh /etc/rc.common

START=14

USE_PROCD=1
NAME=questd
PROG=/sbin/questd

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_close_instance
}

stop() {
	service_stop /sbin/questd
}

reload() {
	service_reload /sbin/questd
}
