#!/bin/sh /etc/rc.common

. /lib/functions.sh
include /lib/network

START=21

vlan_inf_conf() {
	local baseifname
	local vlan8021p
	local vlan8021q
	local routed
	config_get baseifname $1 baseifname
	config_get ifname $1 ifname
	config_get vlan8021p $1 vlan8021p
	config_get vlan8021q $1 vlan8021q
	config_get bridge $1 bridge
	addbrcmvlan "$baseifname" "$vlan8021p" "$vlan8021q" "$bridge" "$ifname"
}

boot() {
	echo "VLAN does not run at boot"
}

start() {
	local vdslstatus
	echo "Starting VLAN"

	config_load layer2_interface_vlan
	config_foreach vlan_inf_conf vlan_interface
}

stop() {
	echo "Stopping VLAN"
	removeall_vlandevices
}

restart() {
	stop
	start
}

