#!/bin/sh
# Copyright (C) 2006-2010 OpenWrt.org

iopsys_rootfs_pivot() {
	[ "$pi_iopsys_skip_overlay" = "true" ] && return
	echo "mounting and populating overlay"
	fopivot /overlay /rom && pi_mount_skip_next=true
}

boot_hook_add preinit_mount_root iopsys_rootfs_pivot

