#!/bin/sh /etc/rc.common

START=12
USE_PROCD=1

migrate_shadow() {
	/bin/sh /rom/etc/uci-defaults/10_migrate-shadow
}

set_password() {
        local usertype="$1"
        local password
	config_get password $usertype password

	[ -n "$password" ] && (echo $password; sleep 1; echo $password) | passwd $usertype >/dev/null 2>&1

	uci delete passwords.$usertype.password >/dev/null 2>&1
}
service_triggers()
{
	procd_add_reload_trigger "passwords"
}

start_service() {
	migrate_shadow
	config_load passwords
	config_foreach set_password usertype
	uci commit passwords
}

