#!/bin/sh /etc/rc.common

. /lib/functions.sh

START=11

convert_etc_passwd() {
	local ngtpswd=""
	if [ -f /etc/ngt/password ]; then
		ngtpswd="$(cat /etc/ngt/password  | tr '\n' ' ' | sed s'/\ //g')"
		if [ -n "$ngtpswd" ]; then
			uci set passwords.root.password="$ngtpswd"
			uci set passwords.admin.password="$ngtpswd"
			uci commit passwords
			echo "" > /etc/ngt/password
		fi
	fi
}

get_mac_adj() {
	local bmac=$(cat /proc/nvram/BaseMacAddr | tr '[a-z]' '[A-Z]')
	bmac=${bmac// /}
	local lmac=$bmac
	local mac="${lmac:0:2}${lmac:2:2}${lmac:4:2}${lmac:6:2}${lmac:8:2}${lmac:10:2}"
	echo $mac
}

get_mac() {
	local bmac=$(cat /proc/nvram/BaseMacAddr | tr '[a-z]' '[A-Z]')
	bmac=${bmac// /}
	local lmac=$bmac
	local mac="${lmac:0:2} ${lmac:2:2} ${lmac:4:2} ${lmac:6:2} ${lmac:8:2} ${lmac:10:2}"
	echo $mac
}

default_ppp_password() {
	local mac="$(get_mac)"
	local pswd="AerP56Gac65"
	local newpswd
	local decval=0
	local tmpval

	for addr in $mac; do
		tmpval=$((0x$addr))
		decval=$(($decval+$tmpval))
	done
	newpswd=$decval$pswd
	echo $newpswd
}

set_ppp_password() {
        local interface="$1"
        local proto mac usrnm pass

	config_get proto $interface proto

	case "$proto" in
		pppo*)
			usrnm="$(uci -q get network.$interface.username)"
			[ -n "$usrnm" ] || {
				mac="$(get_mac_adj)"
				uci set network.$interface.username="$mac@ngtipc01.no"
			}
			pass="$(uci -q get network.$interface.password)"
			[ -n "$pass" ] || {
				pass="$(default_ppp_password)"
				uci set network.$interface.password="$pass"
			}
		;;
	esac
}

start() {
	config_load network
	config_foreach set_ppp_password interface
	uci commit network
}

boot() {
	convert_etc_passwd
	start
}
