#!/bin/sh
#
# ash should die, so should line buffering...
#

datafile="/tmp/neigh.cache"
touch $datafile
touch $datafile.tmp

ip monitor neigh | while read rawline ; do
	entry=`echo "$rawline" | grep -v "^dev" | grep "lladdr" | grep -v "NOARP" | grep -E " (br-lan|wl0\.1) " | cut -d\  -f 1,3,5`

	if [ "$entry" != "" ]; then
		tail -n -200 $datafile | grep -v "$entry" > $datafile.tmp
		echo `date +%s` "$entry" >> $datafile.tmp
		mv $datafile.tmp $datafile
	fi

done
