#!/bin/sh

[ -f /var/dectisregistering ] || {
	touch /var/dectisregistering 2>/dev/null
	/usr/bin/dectmngr -r
	ubus call led.dect  set '{"state" : "notice"}'
	sleep 20
	rm /var/dectisregistering 2>/dev/null
	/usr/bin/dectmngr -s
	ubus call led.dect  set '{"state" : "ok"}'
}
