include $(TOPDIR)/rules.mk

PKG_NAME:=routermodel-eg200
PKG_VERSION:=1.0.0
PKG_MAINTAINER:=Martin K. Schroder <mkschreder.uk@gmail.com>

PKG_LICENSE:=Apache-2.0
PKG_LICENSE_FILES:=

PKG_BUILD_PARALLEL:=1

include $(INCLUDE_DIR)/package.mk

define Build/Prepare
	
endef

define Build/Compile

endef

define Package/routermodel-eg200
	TITLE:=routermodel-eg200
	DEPENDS:= +inteno-base +inteno-base-voice
endef

define Package/routermodel-eg200/config

endef

define Package/routermodel-eg200/description
	
endef

define Package/routermodel-eg200/install
	
endef

define Package/routermodel-eg200/postinst

endef

$(eval $(call BuildPackage,routermodel-eg200))
