include $(TOPDIR)/rules.mk

PKG_NAME:=customer-cg300
PKG_VERSION:=15.6.8
PKG_MAINTAINER:=Martin K. Schroder <mkschreder.uk@gmail.com>

PKG_LICENSE:=Apache-2.0
PKG_LICENSE_FILES:=

PKG_BUILD_PARALLEL:=1

include $(INCLUDE_DIR)/package.mk

define Build/Prepare

endef

define Package/customer-cg300
	CATEGORY:=Configs
  TITLE:=CG300 Customer Base Configs
endef

define Package/customer-cg300/config
	
endef

define Package/customer-cg300/description
	CG300 Customer Base Configuration
endef

define Package/customer-cg300/install
	
endef

define Package/customer-cg300/postinst

endef

$(eval $(call BuildPackage,customer-cg300))
