#!/bin/sh

if [ "$ACTION" == "reg_start" ]; then
    ubus call led.dect set '{"state":"notice"}'
fi

if [ "$ACTION" == "reg_stop" ]; then
    ubus call led.dect set '{"state":"ok"}'
fi

if [ "$ACTION" == "dect_init" ]; then
    ubus call led.dect set '{"state":"ok"}'
fi

