#!/bin/sh

if [ "$ACTION" == "led_blink" ]; then
    ubus call led.dect set '{"state":"notice"}'
fi

if [ "$ACTION" == "led_on" ]; then
    ubus call led.dect set '{"state":"ok"}'
fi

if [ "$ACTION" == "led_off" ]; then
    ubus call led.dect set '{"state":"off"}'
fi


