#!/bin/sh /etc/rc.common

START=19
STOP=91

USE_PROCD=1
NAME=peripheral_manager
PROG=/sbin/peripheral_manager

start_service() {
	procd_open_instance
	procd_set_param command "$PROG" -f
	procd_set_param respawn
	procd_close_instance
}

service_running() {
	ubus -t 2 wait_for leds
	ubus call led.status set '{"state":"ok"}'
}

stop() {
	service_stop /sbin/peripheral_manager
}

