#!/bin/sh /etc/rc.common

START=01
STOP=99

USE_PROCD=1
NAME=iwatchdog
PROG=/sbin/iwatchdog

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn
	procd_close_instance
}

#stop() {
#	service_stop /sbin/iwatchdog
#}

