#!/bin/sh /etc/rc.common
# Copyright (C) 2014 OpenWrt.org

START=10
USE_PROCD=1

validate_system_section()
{
	uci_validate_section system system "${1}" \
		'hostname:string:OpenWrt' \
		'conloglevel:uinteger' \
		'buffersize:uinteger' \
		'timezone:string:UTC' \
		'zonename:string'
}

system_config() {
	local cfg="$1"

	local hostname conloglevel buffersize timezone zonename

	validate_system_section "${1}" || {
		echo "validation failed"
		return 1
	}

	echo "$hostname" > /proc/sys/kernel/hostname
	[ -z "$conloglevel" -a -z "$buffersize" ] || dmesg ${conloglevel:+-n $conloglevel} ${buffersize:+-s $buffersize}
	echo "$timezone" > /tmp/TZ
	[ -n "$zonename" ] && [ -f "/usr/share/zoneinfo/$zonename" ] && ln -s "/usr/share/zoneinfo/$zonename" /tmp/localtime

	# apply timezone to kernel
	date -k

	if [ -x /sbin/syslogd ]; then
		local args log_ip log_size log_port log_type log_file
		config_get log_ip "$cfg" log_ip
		config_get log_size "$cfg" log_size 16
		config_get log_port "$cfg" log_port 514
		config_get log_type "$cfg" log_type circular
		config_get log_file "$cfg" log_file "/var/log/messages"
		args="${log_ip:+-L -R ${log_ip}:${log_port}} ${conloglevel:+-l $conloglevel}"
		if [ "$log_type" = "file" ]; then
			args="$args -s $log_size -O $log_file -S"
		else
			args="$args -C${log_size}"
		fi
		service_start /sbin/syslogd $args
	fi
	if [ -x /sbin/klogd ]; then
		config_get klogconloglevel "$cfg" klogconloglevel
		args="${klogconloglevel:+-c $klogconloglevel}"
		service_start /sbin/klogd $args
	fi
}

reload_service() {
	config_load system
	config_foreach system_config system
}

service_triggers()
{
	procd_add_reload_trigger "system"
	procd_add_validation validate_system_section
}

start_service() {
	reload_service
}

stop_service() {
	service_stop /sbin/klogd
	service_stop /sbin/syslogd
}
