#!/bin/sh 

machack()
{
        local MAC=$(cat /proc/nvram/BaseMacAddr)
        MAC=${MAC// /}
        local NEWMAC=$(printf "%X\n" $((0x$MAC + 3)))
        ADDMAC=$(echo $(printf "%12s\n" $NEWMAC | tr ' ' 0) | sed -e 's/\([0-9A-Fa-f]\{2\}\)/\1:/g' -e 's/\(.*\):$/\1/')
        db set hw.board.BaseMacAddr="$ADDMAC"
        db commit 
}

machack


