include $(TOPDIR)/rules.mk

PKG_NAME:=profile-quarantine
PKG_VERSION:=1.0.0
PKG_MAINTAINER:=Martin K. Schroder <mkschreder.uk@gmail.com>

PKG_LICENSE:=Apache-2.0
PKG_LICENSE_FILES:=

PKG_BUILD_PARALLEL:=1

include $(INCLUDE_DIR)/package.mk

define Build/Prepare
	
endef

define Build/Compile

endef

define Package/profile-quarantine
	TITLE:=profile-quarantine
	DEPENDS:=
endef

define Package/profile-quarantine/config

endef

define Package/profile-quarantine/description
	
endef

define Package/profile-quarantine/install
	
endef

define Package/profile-quarantine/postinst

endef

$(eval $(call BuildPackage,profile-quarantine))
