include $(TOPDIR)/rules.mk

PKG_NAME:=profile-scripts
PKG_VERSION:=1.0.0
PKG_MAINTAINER:=Martin K. Schroder <mkschreder.uk@gmail.com>

PKG_LICENSE:=Apache-2.0
PKG_LICENSE_FILES:=

PKG_BUILD_PARALLEL:=1

include $(INCLUDE_DIR)/package.mk

define Build/Prepare
	
endef

define Build/Compile

endef

define Package/profile-scripts
	TITLE:=profile-scripts
	DEPENDS:=
endef

define Package/profile-scripts/config

endef

define Package/profile-scripts/description
	
endef

define Package/profile-scripts/install
	
endef

define Package/profile-scripts/postinst

endef

$(eval $(call BuildPackage,profile-scripts))
