#!/bin/sh
ENABLE_HOOKS=
DISABLE_HOOKS=

. /lib/functions.sh
. /usr/share/libubox/jshn.sh
. /lib/network/ebtables.sh
[ -f /lib/network/anyfi.sh ] && . /lib/network/anyfi.sh
[ -f /lib/network/anyfi_broadcom.sh ] && . /lib/network/anyfi_broadcom.sh

exec >/dev/null 2>&1

local ALLJOYN="/usr/bin/alljoyn-daemon"
local RESTART="0"
local _enWifi=0
local _enWps=0
local _vno=0
local _cno=0
local staifs=""
local wetifs=""

local daymatch=0
local timematch=0
local current_day=$(date | awk '{print$1}' | tr '[A-Z]' '[a-z]')
local current_time=$(date +%H%M)

nvset() {
	local opt=$(echo $1 | cut -d'=' -f1)
	local val=$(echo $1 | cut -d'=' -f2)
	opt=${opt/./_}
	uci -q set broadcom.nvram."$opt=$val"
}

nvget() {
	local optval="$1"
	optval=${optval/wl0./wl0_}
	optval=${optval/wl1./wl1_}
	uci -q get broadcom.nvram."$optval"
}

nvcommit() {
	uci commit broadcom
}

cleanup() {
	local guestvif="$(nvget wl_guestmgr_ifname)"
	local guestcfg="$(nvget wl_guestmgr_cfgno)"

	# remove all QR code images
	rm -f /www/luci-static/resources/icons/wqr_$1*

	# clean NVRAM parameters
	sed -i "/option $1/ d" /etc/config/broadcom
	[ -n "$1" ] && {
		sed -i "s/$1.[1-255]//g" /etc/config/broadcom
		sed -i "s/$1//g" /etc/config/broadcom
		nvget wl_guestmgr_ifname="$guestvif"
		nvget wl_guestmgr_cfgno="$guestcfg"
	}
	nvset init=1
	nvset debug=0
}

kill_related_daemons() {
	killall -9 wifimngr 2>/dev/null
	killall -9 eapd 2>/dev/null
	killall -9 nas 2>/dev/null
	killall -9 acsd 2>/dev/null
	killall -SIGTERM wps_monitor 2>/dev/null
}

run_acsd() {
	local wldev cchn fchn
	for wldev in $(nvget acs_ifnames); do
		[ $(nvget wl_2g_radio) == "$wldev" ] && continue
		# if initially on a dfs channel switch to first available channel
		cchn=$(wlctl -i $wldev status | grep "Primary" | awk '{print$NF}')
		fchn=$(wlctl -i $wldev chanspecs | head -1 | awk '{print$1}')
		if [ $cchn -ge 52 ]; then
			wlctl -i $wldev down
			wlctl -i $wldev channel $fchn
			wlctl -i $wldev up
		fi
	done
	if [ -n "$(nvget acs_ifnames)" ]; then
		if [ "$RESTART" == "1" ]; then
			acsd &
			return
		else
			acsd
		fi
		for wldev in $(nvget acs_ifnames); do
			# finds appropriate channel candidates
			acs_cli -i $wldev autochannel
			# triggers an early channel switch
			acs_cli -i $wldev autochannel
		done
	fi
}

start_related_daemons() {
	local wps
	config_get_bool wps status wps "1"
	eapd
	nas
	[ $wps -ne 0 -a $_enWps -gt 0 ] && wps_monitor &
	run_acsd
	[ -f $ALLJOYN ] && wifimngr &
}

set_bridge() {
	local br=$1
	brctl stp $br off
	brctl setfd $br 0
	sendarp -s $br -d $br
}

map_networks() {
	# map all interfaces to corresponding networks by nvram parameters
	local ifdev ifobj devtype
	local devs=""
	local _acnt=0
	for ifobj in `ubus list network.interface.\*`; do
		interface="${ifobj##network.interface.}"
		(
			[ "$_acnt" == "0" ] && _acnt=""
			[ "$interface" == "loopback" ] && continue
			json_load "$(ifstatus $interface)"
			json_get_var ifdev device
			if [ -n "$ifdev" ]; then
				nvset lan"$_acnt"_ifname="$ifdev"
				json_load "$(devstatus $ifdev)"
				json_get_var devtype type
				if [ "$devtype" == "Bridge" ]; then
					local _i=1
					set_bridge $ifdev
					json_select bridge-members
					while json_get_var dev $_i; do
						[ -z "$devs" ] && devs="$dev" || devs="$devs $dev"
						_i=$((_i+1))
					done
					nvset lan"$_acnt"_ifnames="$devs"
				else
					nvset lan"$_acnt"_ifnames="$ifdev"
				fi
			fi
		)
		_acnt=$((_acnt+1))
	done
}

netno() {
	local network="$1"
	local ifobj
	local _acnt=0
	for ifobj in `ubus list network.interface.\*`; do
		interface="${ifobj##network.interface.}"
		(
			[ "$_acnt" == "0" ] && _acnt=""
			[ "$interface" == "loopback" ] && continue
			if [ "$interface" == "$network" ]; then
				echo "$_acnt"
				break
			fi
		)
		_acnt=$((_acnt+1))
	done
}

find_network() {
	local device="$1"
	local ifdev ifl3dev ifobj devtype ifname
	for ifobj in `ubus list network.interface.\*`; do
		interface="${ifobj##network.interface.}"
		[ "$interface" == "loopback" ] && continue
		ifname=`uci -q get network.$interface.ifname`
		[ "${ifname:0:1}" == "@" ] && continue
		json_load "$(ifstatus $interface)"
		json_get_var ifdev device
		json_get_var ifl3dev l3_device
		if [ "$device" == "$ifdev" -o "$device" == "$ifl3dev" ]; then
			echo "$interface"
			return
		else
			json_load "$(devstatus $ifdev)"
			json_get_var devtype type
			if [ "$devtype" == "Bridge" ]; then
				local _i=1
				json_select bridge-members
				while json_get_var dev $_i; do
					if [ "$dev" == "$device" ]; then
						echo "$interface"
						return
					fi
					_i=$((_i+1))
				done
			fi
		fi
	done
}

create_qr_code() {
	local wifc=$1
	local wssd=$2
	local wenc=$3
	local wkey=$4
	local whid=$5
	qrencode -o /www/luci-static/resources/icons/wqr_$wifc.png "WIFI:T:$wenc;S:$wssd;P:$wkey;H:$whid;"
}

set_wifi_down() {
	local device="$1"
	local iface
	local network
	[ -n "$2" -a "$device" != "$2" ] && continue
	uci_revert_state wireless "$device"
	wlctl -i $device down
	for iface in $(grep "$device" /proc/net/dev | awk -F':' '{print$1}'); do
		# remove ebtables wme rules
		remove_ebtables_wme_rules $iface
		network="$(find_network $iface)"
		wlctl -i "$iface" bss down
		wlctl -i "$iface" ssid ""
		ifconfig "$iface" down >/dev/null 2>&1 && {
			[ -n "$network" ] && ubus call network.interface."$network" remove_device "{ \"name\": \"$iface\" }" 2>/dev/null && uci_revert_state wireless "$iface"
		}
	done
	ubus call led.wifi  set '{"state" : "off"}'
}

wif_encryption_settings() {
	local vif=$1
	local iface=$2
	local qr_enc="nopass"
	local qr_hidden=false
	local qr_key="no"
	local key=
	local wsec=0
	local wsec_r=0
	local eap=0
	local eap_r=0
	local auth=0
	local mode ssid network hidden enc cipher
	config_get mode "$vif" mode "ap"
	config_get ssid "$vif" ssid
	config_get_bool hidden "$vif" hidden "0"
	config_get enc "$vif" encryption
	config_get cipher "$vif" cipher

	wlctl -i $iface closed $hidden
	[ "$hidden" == "1" ] && qr_hidden=true

	wlctl -i $iface auth 0
	nvset "$iface"_auth=0
	nvset "$iface"_preauth=0
	nvset "$iface"_net_auth_type=1
	nvset "$iface"_wep=disabled
	case "$enc" in
		*wep*)
			wsec_r=1
			wsec=1
			nvset "$iface"_wep=enabled
			config_get key "$vif" key
			case "$enc" in
				*shared*) wlctl -i $iface auth 1; nvset "$iface"_auth=1;;
			esac
			case "$key" in
				[1234])
					for knr in 1 2 3 4; do
						echo "wlctl -i $iface rmwep $((knr-1))" >> /tmp/wepset
						config_get k "$vif" key$knr
						[ "$knr" == "$key" ] && qr_key="$k"
						[ -n "$k" ] || continue
						echo "wlctl -i $iface addwep $((knr-1)) $k" >> /tmp/wepset
					done
					echo "wlctl -i $iface primary_key $((key-1))" >> /tmp/wepset
				;;
				*)
					if [ -n "$key" ]; then
						echo "wlctl -i $iface rmwep 0" >> /tmp/wepset
						echo "wlctl -i $iface addwep 0 $key" >> /tmp/wepset
						echo "wlctl -i $iface primary_key 0" >> /tmp/wepset
						qr_key="$key"
					fi
				;;
			esac
			qr_enc="WEP"
		;;
		*psk*)
			wsec_r=1
			eap=1
			eap_r=1
			config_get key "$vif" key
			config_get gtk "$vif" gtk_rekey "0"
			nvset "$iface"_wpa_gtk_rekey=$gtk
			# psk version + default cipher
			case "$enc" in
				*mixed*|*psk+psk2*) auth=132; wsec=6; nvset "$iface"_akm='psk psk2'; nvset "$iface"_crypto=tkip+aes;;
				*psk2*) auth=128; wsec=4; nvset "$iface"_akm=psk2; nvset "$iface"_crypto=aes;;
				*) auth=4; wsec=2; nvset "$iface"_akm=psk; nvset "$iface"_crypto=tkip;;
			esac
			# cipher override
			case "$cipher" in
				*tkip+aes*|*tkip+ccmp*|*aes+tkip*|*ccmp+tkip*) wsec=6; nvset "$iface"_crypto=tkip+aes;;
				*aes*|*ccmp*) wsec=4; nvset "$iface"_crypto=aes;;
				*tkip*) wsec=2; nvset "$iface"_crypto=tkip;;
			esac
			nvset "$iface"_wpa_psk="$key"
			nvset "$iface"_auth_mode="psk"
			qr_enc="WPA"
			qr_key="$key"
		;;
		*wpa*)
			wsec_r=1
			eap=1
			eap_r=1
			config_get key "$vif" key
			#config_get server "$vif" server
			#config_get port "$vif" port
			config_get rad_serv "$vif" radius_server
			config_get rad_port "$vif" radius_port "1812"
			config_get rad_sec "$vif" radius_secret
			config_get net_reauth "$vif" key net_reauth "36000"
			nvset "$iface"_net_reauth="$net_reauth"
			# wpa version + default cipher
			case "$enc" in
				*mixed*|*wpa+wpa2*) auth=66; wsec=6; nvset "$iface"_akm='wpa wpa2'; nvset "$iface"_crypto=tkip+aes;;
				*wpa2*) auth=64; wsec=4; nvset "$iface"_akm=wpa2; nvset "$iface"_crypto=aes;;
				*) auth=2; wsec=2; nvset "$iface"_akm=wpa; nvset "$iface"_crypto=tkip;;
			esac
			# cipher override
			case "$cipher" in
				*tkip+aes*|*tkip+ccmp*|*aes+tkip*|*ccmp+tkip*) wsec=6; nvset "$iface"_crypto=tkip+aes;;
				*aes*|*ccmp*) wsec=4; nvset "$iface"_crypto=aes;;
				*tkip*) wsec=2; nvset "$iface"_crypto=tkip;;
			esac
			nvset "$iface"_wpa_psk="$key"
			nvset "$iface"_auth_mode="radius"
			nvset "$iface"_radius_ipaddr="$rad_serv"
			nvset "$iface"_radius_port="$rad_port"
			nvset "$iface"_radius_key="$rad_sec"
			qr_enc="WPA"
			qr_key="$key"
		;;
	esac
	[ "$mode" == "sta" ] && nvset "$iface"_auth_mode="none"
	wlctl -i $iface wsec $wsec
	wlctl -i $iface wpa_auth $auth
	wlctl -i $iface wsec_restrict $wsec_r
	wlctl -i $iface eap $eap
	wlctl -i $iface eap_restrict $eap_r

	# create QR code of the Wi-Fi network
	create_qr_code "$iface" "$ssid" "$qr_enc" "$qr_key" "$qr_hidden"
}

wif_general_settings() {
	local vif=$1
	local iface=$2
	local mode ssid network bridged bss_max isolate vlan_mode
	config_get mode "$vif" mode "ap"
	config_get ssid "$vif" ssid
	config_get network "$vif" network
	config_get bss_max "$vif" bss_max "16"
	config_get_bool isolate "$vif" isolate "0"
	config_get_bool vlan_mode "$vif" vlan_mode "0"

	#wlctl -i $iface ssid "$ssid"
	wlctl -i $iface bss_maxassoc "$bss_max"
	wlctl -i $iface ap_isolate "$isolate"
	wlctl -i $iface vlan_mode "$vlan_mode"

	[ "$(uci -q get network.$network.type)" == "bridge" ] && bridged="1"
	[ "$mode" == "sta" -a "$bridged" == "1" ] && mode="wet"
	[ "$mode" == "sta" ] && staifs="$staifs $iface"
	[ "$mode" == "wet" ] && wetifs="$wetifs $iface"

	nvset "$iface"_mode="$mode"
	nvset "$iface"_ifname="$iface"
	nvset "$iface"_ssid="${ssid:-Inteno}"
	nvset "$iface"_radio=1
	nvset "$iface"_infra=1
}

wif_apsta_settings() {
	local vif=$1
	local iface=$2
	local device mode autoconf apsta
	config_get device "$vif" device
	config_get mode "$vif" mode "ap"
	config_get_bool autoconf "$vif" autoconf
	config_get apsta "$device" apsta

	# tag apsta interfaces
	if [ "$apsta" == "1" ]; then
		if [ "$mode" == "sta" ]; then
			# tag sta interface
			nvset wl_apsta_sta_ifname="$iface"
			nvset wl_apsta_sta_cfg="$vif"
			nvset wl_apsta_sta_net="$network"
#		else
#			# tag ap interface
#			nvset wl_apsta_ap_ifname="$iface"
#			nvset wl_apsta_ap_cfg="$vif"
#			nvset wl_apsta_ap_net="$network"
		fi
	fi

	# tag autoconf interfaces
	if [ "$mode" == "ap" -a "$autoconf" == "1" ]; then
		nvset wl_autoconf_ap_ifnames="$iface $(nvget wl_autoconf_ap_ifnames)"
		nvset wl_autoconf_ap_cfgs="$vif $(nvget wl_autoconf_ap_cfgs)"
		nvset wl_autoconf_ap_net="$network"
	fi
}

wif_wps_settings() {
	local vif=$1
	local iface=$2
	local device mode wps_mode lno
	config_get device "$vif" device
	config_get mode "$vif" mode "ap"
	config_get wps_mode "$vif" wps_pbc

	if [ "$wps_mode" == "1" ]; then
		nvset "$iface"_wps_mode="enabled"
		nvset router_disable="0"
		nvset wps_modelnum="123456"
		nvset boardnum="1234"
		nvset wps_modelname="Broadcom"
		nvset wps_mfstring="Broadcom"
		nvset wps_device_name="Inteno"
		nvset wps_version2="enabled"
		lno=$(netno $network)
		nvset lan"$lno"_wps_reg="enabled"
		nvset lan"$lno"_wps_oob="disabled"
		nvset wps_proc_status="0"
		nvset wps_button_gpio="$(db get -q hw.board.wpsButtonGpio)"
		if [ "$(uci -q get wireless.$device.apsta)" == "1" ]; then
			nvset "$device"_ure_mode="wre"
			nvset wps_pbc_apsta="enabled"
			nvset wps_pbc_method="2"
			[ "$mode" == "sta" ] && nvset wps_pbc_sta_ifname="$iface" || nvset wps_pbc_ap_ifname="$iface"
		fi
		nvset wps_oob_configured="1"
		nvset wps_config="DONE"
		_enWps=$((_enWps+1))
	else
		nvset "$iface"_wps_mode="disabled"
	fi
}

wif_macfilter() {
	local vif=$1
	local iface=$2
	local macfilter macmode maclist
	config_get macfilter "$vif" macfilter "0"
	config_get macmode "$vif" macmode "1"
	config_get maclist "$vif" maclist

	wlctl -i $iface macmode $macfilter
	[ "$macfilter" == "1" ] && wlctl -i $iface macmode $macmode
	wlctl -i $iface mac none
	[ -n "$maclist" ] && {
		for mac in $maclist; do
			wlctl -i $iface mac $mac
		done
	}
}

wif_wmx_settings() {
	local vif=$1
	local iface=$2
	local wmf_en wmm_dis
	config_get_bool wmf_en "$vif" wmf_bss_enable "1"
	config_get_bool wmm_dis "$vif" wmm_bss_disable "0"

	# set WMF
	wlctl -i $iface wmf_bss_enable $wmf_en || dhdctl -i $iface wmf_bss_enable $wmf_en
	# set WME
	wlctl -i $iface wme_bss_disable $wmm_dis
}

wif_setup() {
	local vif=$1
	local iface=$2
	local device network disabled vifs wmm
	config_get device "$vif" device
	config_get network "$vif" network
	config_get_bool disabled "$vif" disabled
	config_get wmm "$device" wmm "1"

	# set wireless VIFs in broadcom nvram
	vifs=$(nvget "$device"_vifs)
	[ -z "$vifs" ] && vifs="$iface" || vifs="$vifs $iface"
	nvset "$device"_vifs="$vifs"

	# set VIF UCI state
	# uci_set_state wireless "$vif" up 1
	uci_set_state wireless "$vif" ifname "$iface"

	# add ebtables rules for VIF
	[ "$wmm" == "1" ] && add_ebtables_wme_rules $iface

	# tag VIF network
	nvset "$iface"_network=$network

	# check if VIF is disabled in config
	if [ "$disabled" == "1" ]; then
		nvset "$iface"_bss_enabled=0
	else
		nvset "$iface"_bss_enabled=1
	fi
}

setup_wifi_iface() {
	local vif="$1"
	local device
	local iface
	config_get device "$vif" device

	[ "$2" == "$device" ] || continue

	if [ $_vno -eq 0 ]; then
		iface="$device"
	else
		# multiple SSIDs are used
		iface="$device"."$_vno"
		nvset nas_alternate=1
	fi

	wif_general_settings $vif $iface
	wif_macfilter $vif $iface
	wif_wmx_settings $vif $iface
	wif_encryption_settings $vif $iface
	wif_apsta_settings $vif $iface
	wif_wps_settings $vif $iface
	wif_setup $vif $iface

	_vno=$((_vno+1))
}

mbss_macddr() {
	local device=$1
	local mbssno=$2
	local idx=$3
	local pether start mid dend fend hend xend dec

	pether=$(wlctl -i $device perm_etheraddr | awk '{print$2}')

	if [ $idx -eq 0 ]; then
		echo "$pether"
	else
		start=$(echo $pether | cut -d':' -f1)
		start=$(printf "%d\n" 0x$start)
		start=$((start+2))
		start=$(printf "%0.2x\n" "$start")
		mid=$(echo $pether | cut -d':' -f2,3,4,5)
		xend=$(echo $pether | cut -d':' -f6)
		fend=$(printf "%d\n" 0x$xend)
		dend=$((fend+$idx))
		hend=$(printf "%0.2x\n" "$dend")
		if [ "${hend:0:1}" != "${xend:0:1}" ]; then
			dec=$((mbssno-$idx))
			dend=$((fend-$dec))
			hend=$(printf "%0.2x\n" "$dend")
		fi
		echo "$start:$mid:$hend"
	fi
}

create_vif() {
	local vif="$1"
	local device iface network mbssmac mbssnum
	config_get device "$vif" device
	config_get network "$vif" network

	[ "$2" == "$device" ] || continue

	if [ $_cno -eq 0 ]; then
		iface="$device"
		# tag main interfaces
		local mifs=$(nvget wl_main_ifnames)
		[ -n "$mifs" ] && mifs="$mifs $iface" || mifs="$iface"
		nvset wl_main_ifnames="$mifs"
	else
		iface="$device"."$_cno"
	fi

	mbssnum=$(uci show wireless | grep "wifi-iface" | grep -c "device=$device")
	mbssmac="$(mbss_macddr $device $mbssnum $_cno | tr '[a-z]' '[A-Z]')"

	wlctl -i $device bss -C $_cno down
	wlctl -i $device ssid -C $_cno "Inteno"
	ifconfig $iface down
	ifconfig $iface hw ether $mbssmac

	# save hwaddr for each virtual interface
	nvset "$iface"_hwaddr="$mbssmac"

	# save uci config no for each virtual interface
	nvset "$iface"_cfgno="$vif"

	# tag guest interface
	[ "$network" == "guestMgr" -o "$network" == "guest" ] && {
		nvset wl_guestmgr_ifname="$iface"
		nvset wl_guestmgr_cfgno="$vif"
	}

	_cno=$((_cno+1))
}

wdev_assured_settings() {
	local device=$1
	wlctl -i $device leddc 0
	wlctl -i $device wds none
	wlctl -i $device msglevel 0
	wlctl -i $device phy_watchdog 1
	wlctl -i $device ap 1
	wlctl -i $device mbss 1
}

wdev_static_settings() {
	local device=$1
	wlctl -i $device txbf 0
	wlctl -i $device txbf_bfr_cap 0
	wlctl -i $device txbf_bfe_cap 0
	wlctl -i $device stbc_rx 0
	wlctl -i $device stbc_tx -1
	wlctl -i $device fcache 1 || dhdctl -i $device fcache 1
	wlctl -i $device pktc 1 || dhdctl -i $device pktc 1
	wlctl -i $device wnm 0x103
	wlctl -i $device wet 0
	wlctl -i $device mpc 0
	wlctl -i $device infra 1
	wlctl -i $device closed 0
	wlctl -i $device mimo_preamble 2
	wlctl -i $device gmode_protection 1
	wlctl -i $device gmode_protection_override -1
	wlctl -i $device gmode_protection_control 2
	wlctl -i $device nmode_protection_override -1
	wlctl -i $device protection_control 2
	wlctl -i $device bg_rate 0
	wlctl -i $device mrate 0
	wlctl -i $device bg_mrate 0
	wlctl -i $device afterburner_override 0
	wlctl -i $device amsdu 0
	wlctl -i $device rx_amsdu_in_ampdu 0
	wlctl -i $device ampdu 255
	wlctl -i $device ampdu_tx 255
	wlctl -i $device ampdu_rx 255
	wlctl -i $device ampdu_mpdu 32
	wlctl -i $device rxchain_pwrsave_stas_assoc_check 1
	wlctl -i $device radio_pwrsave_stas_assoc_check 1
	wlctl -i $device noise_metric 1
	wlctl -i $device mpc_dur 0
	wlctl -i $device nar 0
	wlctl -i $device probresp_sw 1
	wlctl -i $device mimo_ps 0
	wlctl -i $device phy_percal_delay 60
}

wdev_radar_settings() {
	local device=$1
	local doth
	config_get doth "$device" doth "1"

	case "$doth" in
		1)
			nvset $device"_reg_mode"="h"
			wlctl -i $device radar 1
			wlctl -i $device regulatory 0
			wlctl -i $device spect 1
		;;
		2)
			nvset $device"_reg_mode"="strict_h"
			wlctl -i $device radar 1
			wlctl -i $device regulatory 0
			wlctl -i $device spect 2
		;;
		3)
			nvset $device"_reg_mode"=""
			wlctl -i $device radar 1
			wlctl -i $device regulatory 1
			wlctl -i $device spect 0
		;;
		*)
			nvset $device"_reg_mode"=""
			wlctl -i $device radar 0
			wlctl -i $device regulatory 0
			wlctl -i $device spect 0
		;;
	esac

	local pcid="$(wlctl -i $device revinfo | awk 'FNR == 2 {print}' | cut -d'x' -f2)"
	local isac="$(db get hw.$pcid.is_ac)"
	if [ "$isac" == "1" ]; then
		wlctl -i $device msglevel +radar +dfs
	fi
	local rdrthrs="$(db get hw.$pcid.radarthrs)"
	if [ -n "$rdrthrs" ]; then
		wlctl -i $device up
		wlctl -i $device radarthrs $rdrthrs
		wlctl -i $device down
	fi
}

wdev_bwcap_settings() {
	local device=$1
	local country band bandwidth obss_coex
	config_get country "$device" country "EU/13"
	config_get band "$device" band "b"
	config_get bandwidth "$device" bandwidth
	config_get obss_coex "$device" obss_coex "1"

	if [ $band == "b" ]; then
		nvset wl_2g_radio="$device"
	else
		nvset wl_5g_radio="$device"
	fi

	wlctl -i $device country $country
	wlctl -i $device band $band
	wlctl -i $device obss_coex $obss_coex
	case "$bandwidth" in
		80)
			wlctl -i $device mimo_bw_cap 2
			wlctl -i $device bw_cap 2g 0x1
			wlctl -i $device bw_cap 5g 0x7
		;;
		40)
			wlctl -i $device mimo_bw_cap 2
			wlctl -i $device bw_cap 2g 0x3
			wlctl -i $device bw_cap 5g 0x3
		;;
		20)
			wlctl -i $device mimo_bw_cap 0
			wlctl -i $device bw_cap 2g 0x1
			wlctl -i $device bw_cap 5g 0x1
		;;
		*)
			wlctl -i $device mimo_bw_cap 0
			wlctl -i $device bw_cap 2g 0x1
			wlctl -i $device bw_cap 5g 0x3
		;;
	esac
}

wdev_hwmode_settings() {
	local device=$1
	local hwmode
	config_get hwmode "$device" hwmode "auto"

	wlctl -i $device gmode 1
	wlctl -i $device nmode -1
	wlctl -i $device nreqd 0
	wlctl -i $device vhtmode 0
	case "$hwmode" in
		*a)
			wlctl -i $device nmode 0
		;;
		*b)
			wlctl -i $device nmode 0
			wlctl -i $device gmode 0
		;;
		*bg)
			wlctl -i $device nmode 0
			wlctl -i $device gmode 1
		;;
		*g)
			wlctl -i $device nmode 0
			wlctl -i $device gmode 2
		;;
		*gst)
			wlctl -i $device gmode 4
		;;
		*lrs)
			wlctl -i $device gmode 5
		;;
		*n)
			wlctl -i $device nmode 1
			wlctl -i $device nreqd 1
		;;
		*ac)
			wlctl -i $device nmode 3
			wlctl -i $device nreqd 1
			wlctl -i $device vhtmode 1
		;;
	esac
}

wdev_channel_settings() {
	local device=$1
	local apsta doth channel scantimer acsifs dfsc bandwidth chanspec

	# if device is in apsta mode, no need for channel settings
	# as it will operate at the channel selected by its master
	config_get apsta "$device" apsta "0"
	if [ "$apsta" == "1" ]; then
		wlctl -i $device chanim_mode 0
		return
	fi

	config_get doth "$device" doth "1"
	config_get channel "$device" channel "auto"
	config_get scantimer "$device" scantimer "15"
	config_get dfsc "$device" dfsc "0"
	config_get bandwidth "$device" bandwidth

	case "$channel" in
		auto)
			acsifs="$(nvget acs_ifnames | sed 's/ *$//')"
			if [ -n "$acsifs" ]; then
				nvset acs_ifnames="$acsifs $device"
			else
				nvset acs_ifnames="$device"
			fi
			nvset "$device"_acs_chan_dwell_time="70"
			nvset "$device"_acs_chan_flop_period="70"
			nvset "$device"_acs_ci_scan_timeout="300"
			nvset "$device"_acs_ci_scan_timer="4"
			nvset "$device"_acs_cs_scan_timer=$((scantimer * 60))
			nvset "$device"_acs_excl_chans=""
			nvset "$device"_acs_scan_entry_expire="3600"
			nvset "$device"_acs_tx_idle_cnt="5"
			nvset "$device"_acs_lowband_least_rssi="-75"
			if [ "$doth" == "0" -o "$dfsc" == "0" ]; then
				nvset "$device"_acs_fcs_mode="1"
				nvset "$device"_acs_dfs="0"
			else
				nvset "$device"_acs_fcs_mode="0"
				nvset "$device"_acs_dfs="1"
				nvset "$device"_acs_dfsr_activity="30 10240"
				nvset "$device"_acs_dfsr_deferred="604800 5"
				nvset "$device"_acs_dfsr_immediate="300 3"
			fi
			wlctl -i $device chanim_mode 2
		;;
		*u|*l|*/80)
			wlctl -i $device chanim_mode 0
			wlctl -i $device chanspec $channel
		;;
		*)
			wlctl -i $device chanim_mode 0
			chanspec="$channel"
			if [ "$bandwidth" == "40" ]; then
				chanspec=$(cat /tmp/wireless/"$device"_chanspecs | grep -w "$channel\"l\"\|$channel\"u\"")
			elif [ "$bandwidth" == "80" ]; then
				chanspec=$(cat /tmp/wireless/"$device"_chanspecs | grep -w "$channel/80")
			fi
			wlctl -i $device chanspec $chanspec
		;;
	esac
}

wdev_rate_settings() {
	local device=$1
	local hwmode rateset rate
	config_get hwmode "$device" hwmode "auto"
	config_get rateset "$device" rateset "default"
	config_get rate "$device" rate "0"

	case "$hwmode" in
		*b) wlctl -i $device rateset default ;;
		*) wlctl -i $device rateset 6b 24 54 ;;
	esac
	wlctl -i $device rate $rate
}

wdev_rifs_settings() {
	local device=$1
	local rifs rifs_advert
	config_get rifs "$device" rifs "0"
	config_get rifs_advert "$device" rifs_advert "0"

	wlctl -i $device rifs $rifs
	wlctl -i $device rifs_advert $rifs_advert
}

wdev_wme_settings() {
	local device=$1
	local wmm wmm_noack wmm_apsd
	config_get wmm "$device" wmm "1"
	config_get wmm_noack "$device" wmm_noack "0"
	config_get wmm_apsd "$device" wmm_apsd "1"

	wlctl -i $device wme $wmm
	wlctl -i $device wme_noack $wmm_noack
	wlctl -i $device wme_apsd $wmm_apsd
}

wdev_tweak_settings() {
	local device=$1
	local fb frag rts dtim bi
	config_get_bool fb "$device" frameburst "0"
	config_get frag "$device" frag "2346"
	config_get rts "$device" rts "2347"
	config_get dtim "$device" dtim_period "1"
	config_get bi "$device" beacon_int "100"

	wlctl -i $device rtsthresh $rts
	wlctl -i $device fragthresh $frag
	wlctl -i $device dtim $dtim
	wlctl -i $device bi $bi
	wlctl -i $device frameburst $fb
}

wdev_antenna_settings() {
	local device=$1
	local rxant txant
	config_get rxant "$device" rxantenna "3"
	config_get txant "$device" txantenna "3"

	wlctl -i $device antdiv $rxant
	wlctl -i $device txant $txant
}

wdev_power_settings() {
	local device=$1
	local txpwr rxcps rxcps_qt rxcps_pps
	config_get txpwr "$device" txpower "100"
	config_get rxcps "$device" rxchainps "0"
	config_get rxcps_qt "$device" rxchainps_qt "10"
	config_get rxcps_pps "$device" rxchainps_pps "10"

	wlctl -i $device pwr_percent $txpwr
	wlctl -i $device rxchain_pwrsave_enable $rxcps
	wlctl -i $device rxchain_pwrsave_quiet_time $rxcps_qt
	wlctl -i $device rxchain_pwrsave_pps $rxcps_pps
}

wdev_wds_settings() {
	local device=$1
	local wds
	config_get wds "$device" wds

	wlctl -i $device wds none
	wlctl -i $device wdswsec 0
	wlctl -i $device wdswsec_enable 0
	wlctl -i $device wdstimeout 1
}

wdev_assoc_settings() {
	local device=$1
	local maxassoc
	config_get maxassoc "$device" maxassoc "16"

	wlctl -i $device maxassoc $maxassoc
}

wdev_apsta_settings() {
	local device=$1
	local apsta
	config_get apsta "$device" apsta "0"

	wlctl -i $device apsta $apsta
	nvset "$device"_apsta=$apsta
}

wdev_wif_bringup() {
	local device=$1
	local vifs=$(nvram get "$device"_vifs)
	local iface network bss

	for iface in $vifs; do
		network=$(nvram get "$iface"_network)
		bss=$(nvram get "$iface"_bss_enabled)
		ssid="$(nvram get "$iface"_ssid)"

		ifconfig "$iface" up >/dev/null 2>&1 && {
			[ -n "$network" ] && ubus call network.interface."$network" add_device "{ \"name\": \"$iface\" }" 2>/dev/null
		}

		if [ $bss -eq 1 ]; then
			wlctl -i $iface ssid "$ssid"
			wlctl -i $iface bss up
		else
			wlctl -i $iface ssid ""
			wlctl -i $iface bss down
		fi
	done
}

setup_wifi_device() {
	local device="$1"
	local disabled wlan
	config_get_bool disabled "$device" disabled "0"
	config_get_bool wlan status wlan "1"

	[ -n "$2" -a "$device" != "$2" ] && continue

	# bring down wireless device
	wlctl -i $device down

	if [ "$RESTART" == "0" ]; then
		wdev_assured_settings $device
	fi

	# create virtual wireless interfaces
	wlctl -i $device up
	config_foreach create_vif wifi-iface "$device"
	wlctl -i $device down
	_cno=0

	[ $wlan -eq 0 -o $disabled -eq 1 ] && continue || _enWifi=$((_enWifi+1))

	if [ "$RESTART" == "0" ]; then
		wdev_static_settings $device
		wdev_radar_settings $device
		wdev_antenna_settings $device
		wdev_wds_settings $device
	fi

	wdev_bwcap_settings $device
	wdev_hwmode_settings $device
	wdev_channel_settings $device
	wdev_rifs_settings $device
	wdev_wme_settings $device
	wdev_tweak_settings $device
	wdev_power_settings $device
	wdev_assoc_settings $device
	wdev_apsta_settings $device
	wdev_rate_settings $device

	# setup virtual wireless interfaces
	config_foreach setup_wifi_iface wifi-iface "$device"
	_vno=0

	# bring up wireless device
	wlctl -i $device up

	# bring up wireless virtual interfaces
	wdev_wif_bringup $device
}

configure_wep() {
	case "$1" in
		init)
			echo "#/bin/sh" > /tmp/wepset
			chmod u+x /tmp/wepset
		;;
		set)
			# set wepkeys if configured
			if [ -f /tmp/wepset ]; then
				sh /tmp/wepset
				rm /tmp/wepset
			fi
		;;
	esac
}

# Run all hook functions $2...$N for each config entry $1
run_hooks() {
	local arg="$1"; shift
	for func in "$@"; do
		config_foreach $func $arg
	done
}

wireless_sta() {
	local dhprc staif wetif

	for staif in $staifs; do
		dhprc="$(ps | grep udhcpc | grep -w $staif | awk '{print$1}')"
		if [ -n "$dhprc" ]; then
			wlctl -i $staif bss up
			kill -9 $dhprc
		fi
	done

	for wetif in $wetifs; do
		wlctl -i $wetif wet 1
		wlctl -i $wetif bss up
	done
}

wifi_updown() {
	local action="$1"
	local wdev="$2"

	cleanup $wdev
	kill_related_daemons

	config_load wireless

	# disable wireless device
	config_foreach set_wifi_down wifi-device $wdev
	run_hooks wifi-device $DISABLE_HOOKS # ANYFI

	# handle wireless led
	ubus call led.wifi  set '{"state" : "off"}'
	if [ "$action" == "disable" ]; then
		[ -n "$(nvget wl_2g_radio)" ] && ubus call led.wifi  set '{"state" : "ok"}'
		[ -n "$(nvget wl_5g_radio)" ] && ubus call led.wifi  set '{"state" : "eok"}'
		return
	fi

	# enable wireless device
	configure_wep "init"
	config_foreach setup_wifi_device wifi-device $wdev
	configure_wep "set"
	nvset wlmngr=done

	# handle wireless led
	ubus call led.eco set '{"state" : "off"}'
	if [ $_enWifi -le 0 ]; then
		ubus call led.eco set '{"state" : "ok"}'
		return
	else
		[ -n "$(nvget wl_2g_radio)" ] && ubus call led.wifi  set '{"state" : "ok"}'
		[ -n "$(nvget wl_5g_radio)" ] && ubus call led.wifi  set '{"state" : "eok"}'
	fi

	map_networks
	run_hooks wifi-device $ENABLE_HOOKS # ANYFI
	nvcommit
	start_related_daemons
	wireless_sta
}

wifi_reload_legacy() {
	wifi_updown "disable" "$1"
	wifi_updown "enable" "$1"
}

wifi_reload() {
	#ubus call network reload
	wifi_reload_legacy
}

wifi_detect() {
	local WLDIR="/tmp/wireless"
	local wls="wl0 wl1"
	local vnos="0 1 2 3 4 5 6 7 8"
	local bands band bwidth country hwmode pcid wl bno doth dfsc scntmr freq ch vdev vn
	local BMAC=$(cat /proc/nvram/BaseMacAddr | tr '[a-z]' '[A-Z]')
	local DMAC=$(echo $BMAC | awk '{print$NF}')
	BMAC=${BMAC// /}
	local BSSID=$(printf "%X\n" $((0x$BMAC + 2)))
	local BSSID4=${BSSID:6:4}
	local BSSID6=${BSSID:4:6}
	local DECIMAL=$(printf "%d\n" 0x${DMAC/:/})
	DECIMAL=$((DECIMAL+100))
	local WPAKEY=$(cat /proc/nvram/WpaKey)
	WPAKEY="${WPAKEY:-1234567890}"
	local SSID="$(uci -q get wireless.@wifi-iface[0].ssid)"
	local ENCR="$(uci -q get wireless.@wifi-iface[0].encryption)"
	local KEY="$(uci -q get wireless.@wifi-iface[0].key)"
	local GTK="$(uci -q get wireless.@wifi-iface[0].gtk_rekey)"
	local WPS="$(uci -q get wireless.@wifi-iface[0].wps_pbc)"
	local NET="$(uci -q get wireless.@wifi-iface[0].network)"

	local PSID="$(uci -q get wireless.preferred.ssid)"
	local PENC="$(uci -q get wireless.preferred.enc)"
	local PKEY="$(uci -q get wireless.preferred.key)"
	local PGTK="$(uci -q get wireless.preferred.gtk)"
	local PWPS="$(uci -q get wireless.preferred.wpsb)"
	local PHW5="$(uci -q get wireless.preferred.hw5g)"
	local PHW2="$(uci -q get wireless.preferred.hw2g)"
	local PBW5="$(uci -q get wireless.preferred.bw5g)"
	local PBW2="$(uci -q get wireless.preferred.bw2g)"
	local PCH5="$(uci -q get wireless.preferred.ch5g)"
	local PCH2="$(uci -q get wireless.preferred.ch2g)"
	local PDFS="$(uci -q get wireless.preferred.dfsc)"
	local PCNT="$(uci -q get wireless.preferred.country)"
	local PTMR="$(uci -q get wireless.preferred.scntmr)"
	local PEXT="$(uci -q get wireless.preferred.extrassid)"
	local PGST="$(uci -q get wireless.preferred.guest)"

	[ -n "$SSID" ] || SSID="${PSID:-Inteno-$BSSID4}"
	[ -n "$ENCR" ] || ENCR=$PENC
	[ -n "$KEY" ] || KEY=$PKEY
	[ -n "$GTK" ] || GTK=$PGTK
	[ -n "$WPS" ] || WPS=$PWPS

	# zero PEXT tag if not dual wifi
	wlctl -i wl1 ap >/dev/null 2>&1 || PEXT="0"

	pcID() {
		wlctl -i $1 revinfo | awk 'FNR == 2 {print}' | cut -d'x' -f2
	}
	is5G() {
		[ "$(db get hw.$1.bands)" == "a" ] && return 0 || return 1
	}
	isAC() {
		[ "$(db get hw.$1.is_ac)" == "1" ] && return 0 || return 1
	}
	populate_chanspecs() {
		wlctl -i $1 country $country
		wlctl -i $1 chanspecs -b $bno -w 20 | awk '{print$1}' > /$WLDIR/$1"_chanspecs"
		wlctl -i $1 chanspecs -b $bno -w 40 | awk '{print$1}' >> /$WLDIR/$1"_chanspecs"
		wlctl -i $1 chanspecs -b $bno -w 80 | awk '{print$1}' >> /$WLDIR/$1"_chanspecs"
		sed -i '/^$/d' /$WLDIR/$1"_chanspecs"
	}

	mkdir -p $WLDIR
	for wl in $wls; do
		if wlctl -i $wl ap >/dev/null 2>&1; then
			pcid=$(pcID $wl)
			country="${PCNT:-EU/13}"
			scntmr="${PTMR:-120}"
			if $(is5G $pcid); then
				freq="5G"
				hwmode="${PHW5:-auto}"
				band="a"
				bwidth="${PBW5:-40}"
				ch="${PCH5:-auto}"
				bno=5
				doth="1"
				dfsc="${PDFS:-1}"
				$(isAC $pcid) && hwmode="${PHW5:-11ac}"
			else
				freq="2.4G"
				hwmode="${PHW2:-auto}"
				band="b"
				bwidth="${PBW2:-20}"
				ch="${PCH2:-auto}"
				bno=2
				doth="0"
				dfsc=""
			fi
			populate_chanspecs $wl
			if ! uci -q get wireless.$wl; then
				cat >> /etc/config/wireless <<EOF
config wifi-device '$wl'
	option type 'broadcom'
	option country '$country'
	option band '$band'
	option bandwidth '$bwidth'
	option hwmode '$hwmode'
	option channel '$ch'
	option scantimer '$scntmr'
	option wmm '1'
	option wmm_noack '0'
	option wmm_apsd '0'
	option txpower '100'
	option rateset 'default'
	option frag '2346'
	option rts '2347'
	option dtim_period '1'
	option beacon_int '100'
	option rxchainps '0'
	option rxchainps_qt '10'
	option rxchainps_pps '10'
	option rifs '0'
	option rifs_advert '0'
	option maxassoc '32'
	option doth '$doth'

EOF
				fi
				if [ "$PGST" == "1" ]; then
					cat >> /etc/config/wireless <<EOF
config wifi-iface
	option device '$wl'
	option network '${NET:-lan}'
	option mode 'ap'
	option ssid '${SSID}'
	option encryption '${ENCR:-mixed-psk}'
	option cipher 'auto'
	option key '${KEY:-$WPAKEY}'
	option gtk_rekey '${GTK:-3600}'
	option macfilter '0'
	option wps_pbc '${WPS:-1}'
	option wmf_bss_enable '1'
	option bss_max '16'

EOF
				if [ "$PEXT" == "1" ]; then
					cat >> /etc/config/wireless <<EOF
config wifi-iface
	option device '$wl'
	option network '${NET:-lan}'
	option mode 'ap'
	option ssid '${SSID}-$freq'
	option encryption '${ENCR:-mixed-psk}'
	option cipher 'auto'
	option key '${KEY:-$WPAKEY}'
	option gtk_rekey '${GTK:-3600}'
	option macfilter '0'
	option wps_pbc '0'
	option wmf_bss_enable '1'
	option bss_max '16'

EOF
				fi
				if [ "$PGST" == "1" ]; then
					cat >> /etc/config/wireless <<EOF
config wifi-iface
	option device '$wl'
	option network 'guest'
	option mode 'ap'
	option ssid '${SSID}-Guest'
	option encryption 'none'
	option macfilter '0'
	option wps_pbc '0'
	option wmf_bss_enable '1'
	option bss_max '16'
	option disabled '1'

EOF
				fi
				uci -q set wireless.$wl.dfsc="$dfsc"
			else
				uci -q set wireless.$wl.band="$band"
				uci -q set wireless.$wl.doth="$doth"
			fi
		else
			uci -q delete wireless.$wl
			for vn in $vnos; do
				vdev="$(uci get wireless.@wifi-iface[$vn].device)"
				if [ $vdev == "$wl" ]; then
					uci -q delete wireless.@wifi-iface[$vn]
				fi
			done
		fi
	done
	uci -q delete wireless.preferred
	uci commit wireless
	sed -i "s/\$DECIMAL/$DECIMAL/g" /etc/config/wireless
	sed -i "s/\$BSSID6/$BSSID6/g" /etc/config/wireless
	sed -i "s/\$BSSID4/$BSSID4/g" /etc/config/wireless
	sed -i "s/\$BSSID2/$BSSID2/g" /etc/config/wireless
	sed -i "s/\$BSSID/$BSSID/g" /etc/config/wireless
	touch /tmp/wireless/first
}

#wifi_onoff() {
#	local status="$1"
#	[ "$status" == "on" ] && status="1" || status="0"
#	local dualwf="$(uci -q get wireless.wl1)"
#	local wl0sta="$(uci -q get wireless.wl0.disabled)"
#	local wl1sta="$(uci -q get wireless.wl1.disabled)"
#	[ -n "$dualwf" ] || wl1sta="$wl0sta"
#	[ -n "$wl0sta" ] || wl0sta="1"
#	[ -n "$wl1sta" ] || wl1sta="1"

#	if [ "$wl0sta" == "$wl1sta" -a "$status" == "$wl0sta" ]; then
#		return
#	fi

#	uci -q set wireless.wl0.disabled="$status"
#	uci -q set wireless.wl1.disabled="$status"
#	uci commit wireless

#	wifi_updown "disable"
#	[ "$status" == "1" ] && wifi_updown "enable"
#}

wifi_onoff() {
	local status="$1"
	[ "$status" == "on" ] && status="1" || status="0"
	local cursta="$(uci -q get wireless.status.wlan)"
	cursta="${cursta:-1}"

	if [ "$status" == "$cursta" ]; then
		return
	fi

	uci -q set wireless.status.wlan="$status"
	uci commit wireless

	wifi_updown "disable"
	[ "$status" == "1" ] && wifi_updown "enable"
}

wifi_toggle_iface() {
	[ -z "$2" ] && return
	local wif="$2"
	local wdev="${wif:0:3}"
	local ssid="$(nvget "$wif"_ssid)"
	if [ "$1" == "disable" ]; then
		nvset "$wif"_bss_enabled=0
		wlctl -i $wif ssid ""
		wlctl -i $wif bss down
	else
		nvset "$wif"_bss_enabled=1
		wlctl -i $wif ssid "$ssid"
		wlctl -i $wif bss up
	fi
	nvcommit
}

day_to_number() {
	case $1 in
		all)		echo 0-6 ;;
		weekdays)	echo 1-5 ;;
		weekend)	echo 0,6 ;;
		sun*)		echo 0 ;;
		mon*)		echo 1 ;;
		tue*)		echo 2 ;;
		wed*)		echo 3 ;;
		thu*)		echo 4 ;;
		fri*)		echo 5 ;;
		sat*)		echo 6 ;;
		*)		echo error ;;
	esac
}

set_wifi_schedule() {
	local cfg="$1"
	local status="$2"
	local days time start stop start_hour stop_hour start_min stop_min
	local sta revsta day dayn dayns

	config_get days $cfg days
	config_get time $cfg time

	if [ "$status" == "1" ]; then
		sta="on"
		revsta="off"
	else
		sta="off"
		revsta="on"
	fi

	start=$(echo $time | awk -F '[ ,-]' '{print$1}')
	stop=$(echo $time | awk -F '[ ,-]' '{print$2}')

	start_hour=$(echo $start | awk -F ':' '{print$1}')
	start_min=$(echo $start | awk -F ':' '{print$2}')

	stop_hour=$(echo $stop | awk -F ':' '{print$1}')
	stop_min=$(echo $stop | awk -F ':' '{print$2}')

	daymatch=0
	for day in $days; do
		[ "${day:0:3}" == "$current_day" ] && daymatch=1
		dayn=$(day_to_number $day)
		[ -n "$dayns" ] && dayns="$dayns,$dayn" || dayns="$dayn"
	done

	if [ $daymatch -eq 1 -a $current_time -gt ${start/:/} -a $current_time -lt ${stop/:/} ]; then
		timematch=1
		uci -q set wireless.status.wlan="$status"
		uci commit wireless
	fi

	echo "$start_min $start_hour * * $dayns wifi $sta # WiFi_Schedule" >> /etc/crontabs/root
	echo "$stop_min $stop_hour * * $dayns wifi $revsta # WiFi_Schedule" >> /etc/crontabs/root

	/etc/init.d/cron reload
}

wifi_schedule() {
	local schedule sched_status revstatus

	sed -i "/WiFi_Schedule/ d" /etc/crontabs/root

	config_load wireless

	config_get_bool schedule status schedule "0"

	[ $schedule == "0" ] && return

	config_get_bool sched_status status sched_status "0"

	config_foreach set_wifi_schedule wifi-schedule $sched_status

	if [ $timematch -eq 0 ]; then
		[ $sched_status == "1" ] && revstatus="0" || revstatus="1"
		uci -q set wireless.status.wlan="$revstatus"
		uci commit wireless
	fi
}

check_md5sum() {
	local old_md5sum="$(cat /tmp/wireless/md5sum 2>/dev/null)"
	local new_md5sum="$(md5sum /etc/config/wireless | awk '{print$1}')"

	if [ "$old_md5sum" == "$new_md5sum" ]; then
		exit
	else
		echo $new_md5sum >/tmp/wireless/md5sum
	fi
}

case "$1" in
	on|off) wifi_onoff "$1"; exit ;;
	detect) wifi_detect; exit ;;
	*) wifi_schedule ;;
esac

if [ -f /tmp/wireless/first ]; then
	RESTART="0"
	rm -f /tmp/wireless/md5sum
	rm -f /tmp/wireless/first
fi

case "$1" in
	disable|enable) wifi_toggle_iface "$1" "$2" ;;
	down) wifi_updown "disable" "$2" ;;
	reload) check_md5sum; wifi_reload "$2" ;;
	reload_legacy) wifi_reload_legacy "$2" ;;
	*) ubus call network reload; wifi_updown "enable" "$2";;
esac

