include $(TOPDIR)/rules.mk

PKG_NAME:=routermodel-dg150
PKG_VERSION:=1.0.0
PKG_MAINTAINER:=Martin K. Schroder <mkschreder.uk@gmail.com>

PKG_LICENSE:=Apache-2.0
PKG_LICENSE_FILES:=

PKG_BUILD_PARALLEL:=1

include $(INCLUDE_DIR)/package.mk

define Build/Prepare
	
endef

define Build/Compile

endef

define Package/routermodel-dg150
	TITLE:=routermodel-dg150
	DEPENDS:= +inteno-base 
endef

define Package/routermodel-dg150/config

endef

define Package/routermodel-dg150/description
	Router model support package
endef

define Package/routermodel-dg150/install
	
endef

define Package/routermodel-dg150/postinst

endef

$(eval $(call BuildPackage,routermodel-dg150))
