#!/bin/sh

. /lib/functions/network.sh

reload_services() {
	[ -f /etc/config/provisioning ] && /etc/init.d/iup reload
	[ -f /etc/config/system ] && /etc/init.d/sysntpd reload
	[ -e /var/run/asterisk/asterisk.ctl ] && /etc/init.d/asterisk reload
	[ -f /etc/config/mcpd ] && /etc/init.d/mcpd reload
	[ -f /etc/config/cwmp ] && /usr/sbin/freecwmp get cache InternetGatewayDevice.WANDevice. &
	[ -f /etc/config/cwmp ] && /usr/sbin/freecwmp get cache InternetGatewayDevice.X_INTENO_SE_IpAccCfg. &
	[ -f /etc/config/cwmp ] && /etc/init.d/cwmpd reload &
}

local IFACE=$1

mkdir -p /tmp/ipv4

local previpaddr=""
local curipaddr=""
local ipaddrfile=/tmp/ipv4/$IFACE-ipaddr
previpaddr=$(cat $ipaddrfile 2>/dev/null)
network_get_ipaddr curipaddr $IFACE
[ -n "$curipaddr" ] && echo $curipaddr > $ipaddrfile || rm -f $ipaddrfile

local prevgateway=""
local curgateway=""
local gatewayfile=/tmp/ipv4/$IFACE-gateway
prevgateway=$(cat $gatewayfile 2>/dev/null)
network_get_gateway curgateway $IFACE
[ -n "$curgateway" ] && echo $curgateway > $gatewayfile || rm -f $gatewayfile

local prevsubnets=""
local cursubnets=""
local subnetsfile=/tmp/ipv4/$IFACE-subnets
prevsubnets=$(cat $subnetsfile 2>/dev/null)
network_get_subnets cursubnets $IFACE
[ -n "$cursubnets" ] && echo $cursubnets > $subnetsfile || rm -f $subnetsfile

[ "$previpaddr" = "$curipaddr" -a "$prevgateway" = "$curgateway" -a "$prevsubnets" = "$cursubnets" ] && exit 0

reload_services

