#!/bin/sh /etc/rc.common

. /lib/functions.sh

START=98

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

boot() {
	start
}


start() {
	service_start /sbin/statd
}


stop() {
	service_stop /sbin/statd
}


restart() {
	stop
	start

}

