#!/bin/sh
. /usr/share/libubox/jshn.sh

local comdev
local atcmnds="sysinfo getoperator getstrength"

test_connection() {
	ping -q -w 5 -c 1 telia.se >/dev/null 2>&1 && return 0
	ping -q -w 5 -c 1 google.se >/dev/null 2>&1 && return 0
	return 1
}

write_date() {
	echo "-----------------" >> /var/m2msupervision.log
	date +%y.%m.%d-%H:%M:%S >> /var/m2msupervision.log
	echo "-----------------" >> /var/m2msupervision.log
}

while true; do
	uci -q get network.mobile >/dev/null || break
	comdev=$(uci get network.mobile.comdev)

	while true; do
		[ -e $comdev ] && break
		sleep 5
	done

	json_load "$(ifstatus mobile)"
	json_get_var uptime uptime
	json_close_object
#	if [ -z "$uptime" ]; then
#		sleep 30
#		json_load "$(ifstatus mobile)"
#		json_get_var up up
#		json_close_object
#		if [ "$up" == "0" ]; then
#			write_date
#			echo "Restarting the modem" >> /var/m2msupervision.log
#			gcom -d $comdev -s /etc/gcom/reset.gcom
#			ifup mobile
#		fi
#	fi
	if [ $uptime -ge 600 ]; then
		test_connection
		if [ "$?" == "0" ]; then
			write_date
			for at in $atcmnds; do
				gcom -d $comdev -s /etc/gcom/$at.gcom >> /var/m2msupervision.log
			done
		else
			write_date
			echo "Restarting the modem" >> /var/m2msupervision.log
			ifdown mobile
			gcom -d $comdev -s /etc/gcom/reset.gcom
			ifup mobile
		fi
	fi
	sleep 600
done
