include $(TOPDIR)/rules.mk

PKG_NAME:=profile-include
PKG_VERSION:=1.0.0
PKG_MAINTAINER:=Martin K. Schroder <mkschreder.uk@gmail.com>

PKG_LICENSE:=Apache-2.0
PKG_LICENSE_FILES:=

PKG_BUILD_PARALLEL:=1

include $(INCLUDE_DIR)/package.mk

define Build/Prepare
	
endef

define Build/Compile

endef

define Package/profile-include
	TITLE:=profile-include
	DEPENDS:=
endef

define Package/profile-include/config

endef

define Package/profile-include/description
	
endef

define Package/profile-include/install
	
endef

define Package/profile-include/postinst

endef

$(eval $(call BuildPackage,profile-include))
