#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=99


start() {

	board=$(db get hw.board.hardware)

	if [ "$board" = "EG300" ]
	then
		id=$(ethctl phy ext 0x1c 0x2 2>&1 | cut -d\  -f5)
		if [ "0xffff" = "$id" ]
		then
			logger "phy_check: can't talk to wan phy chip."
			ubus call led.status set '{"state":"error"}'
		else
			logger "phy_check: OK."
		fi
	fi
}
