#!/bin/sh /etc/rc.common

START=20
USE_PROCD=1

service_triggers()
{
	procd_add_reload_trigger "boardpanel"
}

start_service() {
	local status_led power_led power_led_br brightness

	config_load boardpanel
	config_get_bool status_led "settings" status_led
	config_get_bool power_led "settings" power_led
	config_get power_led_br "settings" power_led_br

	if [ $status_led -eq 0 ]; then
		ubus call leds set  '{"state" : "alloff"}'
	else
		ubus call leds set  '{"state" : "normal"}'
	fi
	
	if [ $power_led -eq 0 ]; then
		ubus call led.power set '{"state": "off"}'
	else
		ubus call led.power set '{"state": "notice"}'
		ubus call led.power set "{\"brightness\":${power_led_br:-100}}"
	fi
}

