#!/bin/sh /etc/rc.common

START=10
USE_PROCD=1

handle_threads()
{
	# initialize kernel schedule priorities
	smd -s

	local pid_nic0=$(pgrep wl0-kthrd)
	local pid_nic1=$(pgrep wl1-kthrd)
	local pid_dhd0=$(pgrep dhd0_dpc)
	local pid_dhd1=$(pgrep dhd1_dpc)
	local pid_wfd0=$(pgrep wfd0-thrd)
	local pid_wfd1=$(pgrep wfd1-thrd)
	local pid_wl0=${pid_dhd0:-$pid_nic0}
	local pid_wl1=${pid_dhd1:-$pid_nic1}

	# set affinity
	if [ -n "$pid_wl0" -a -n "$pid_wl1" ]; then
		# bind to TP0
		taskset -p $pid_wl0 1
		# bind to TP1
		taskset -p $pid_wl1 2
	else
		if [ $pid_wl0 == $pid_dhd0 ]; then
			# bind to TP0
			taskset -p $pid_wl0 1
		else
			# bind to TP1
			taskset -p $pid_wl0 2
		fi
	fi

	# set priority
	local pid pids
	pids="$pid_wl0 $pid_wl1 $pid_wfd0 $pid_wfd1"
	for pid in $pids; do
		chrt -rp 5 $pid
	done
}

handle_configs()
{
	local BMAC=$(cat /proc/nvram/BaseMacAddr | tr '[a-z]' '[A-Z]')
	BMAC=${BMAC// /}
	local MAC=$(printf "%X\n" $((0x$BMAC)))
	local BSSID=$(printf "%X\n" $((0x$BMAC + 2)))
	local WPAKEY=$(cat /proc/nvram/WpaKey)
	local SERIALNR=$(cat /proc/nvram/SerialNumber)
	local HWVER=$(db get hw.board.hardwareVersion)
	local RMODEL=$(db get hw.board.routerModel)
	local DESKEY=$(db get hw.board.desKey)

	local oid=${BMAC:0:6}
	local mac=$BMAC
	local mac2=${MAC:8:2}
	local mac4=${MAC:6:4}
	local mac6=${MAC:4:6}
	local bssid=$BSSID
	local bssid2=${BSSID:8:2}
	local bssid4=${BSSID:6:4}
	local bssid6=${BSSID:4:6}
	local wpakey="${WPAKEY:-1234567890}"
	local hardwareid=$HWVER-$(echo $RMODEL | sed -r 's;.+-(.+);\1;')

	local configs="passwords network wireless system cwmp provisioning"

	for config in $configs; do
		if [ -f /etc/config/$config ]; then
			sed -i "s/\$MAC6/$mac6/g" /etc/config/$config
			sed -i "s/\$MAC4/$mac4/g" /etc/config/$config
			sed -i "s/\$MAC2/$mac2/g" /etc/config/$config
			sed -i "s/\$MAC/$mac/g" /etc/config/$config
			sed -i "s/\$BSSID6/$bssid6/g" /etc/config/$config
			sed -i "s/\$BSSID4/$bssid4/g" /etc/config/$config
			sed -i "s/\$BSSID2/$bssid2/g" /etc/config/$config
			sed -i "s/\$BSSID/$bssid/g" /etc/config/$config
			sed -i "s/\$WPAKEY/$wpakey/g" /etc/config/$config
			sed -i "s/\$DESKEY/$DESKEY/g" /etc/config/$config
			sed -i "s/\$SER/$SERIALNR/g" /etc/config/$config
			sed -i "s/\$OUI/$oid/g" /etc/config/$config
			sed -i "s/\$HARDWAREID/$hardwareid/g" /etc/config/$config
			[ "$config" == "wireless" ] && sed -i "s/pskmixedpsk2/mixed-psk/g" /etc/config/$config
		fi
	done
}

handle_upgrade_count() {
	if cat /proc/cmdline |grep -q ubi:rootfs_0; then
		brcm_fw_tool -s -1 update /dev/mtd0
	elif cat /proc/cmdline |grep -q ubi:rootfs_1; then
		brcm_fw_tool -s -1 update /dev/mtd1
	else
		ls /cferam* | awk -F'.' '{print$NF}'
	fi
}

start_service() {
	handle_upgrade_count
	handle_threads
	handle_configs
}

reload_service() {
        handle_configs
}

